[package]
name = "slowpoke"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: Shrink tokio feature set?
tokio = { version = "=1.13.0", features = ["full"] }
warp = "=0.3.2"
log = "=0.4.14"
pretty_env_logger = "=0.4.0"
